simplesocial/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "accounts"

urlpatterns = [
    path('login', auth_views.LoginView.as_view(
        template_name='accounts/login.html'), name="login"),
    path('logout', auth_views.LogoutView.as_view(
        template_name='accounts/logout.html'), name="logout"),
    path('signup', views.UserRegister.as_view(), name="signup"),
]

simplesocial/groups/urls.py
from django.urls import path
from . import views

app_name = 'groups'

urlpatterns = [
    path('', views.ListGroup.as_view(), name='all'),
    path('new/', views.CreateGroup.as_view(), name='create'),
    path('posts/<slug:slug>', views.SingleGroup.as_view(), name='single')
]

simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls')),
]

simplesocial/accounts/models.py
from django.db import models
from django.contrib.auth.models import User


def get_name(self):
    return "@{}".format(self.username)


User.add_to_class("__str__", get_name)

# Create your models here.

simplesocial/groups/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.


class Group(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    members = models.ManyToManyField(User, through="GroupMember")

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("groups:single", kwargs={"slug": self.slug})

    class Meta:
        ordering = ["name"]


class GroupMember(models.Model):
    group = models.ForeignKey(Group, related_name="memberships")
    user = models.ForeignKey(User, related_name='user_groups')

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ("group", "user")

simplesocial/posts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from groups.models import Group

# Create your models here.


class Post(models.Model):
    user = models.ForeignKey(User, related_name="posts")
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    group = models.ForeignKey(
        Group, related_name="posts", null=True, blank=True)

    def __str__(self):
        return self.message

    def get_absolute_url(self):
        return reverse(
            "posts:single",
            kwargs={
                "username": self.user.username,
                "pk": self.pk
            }
        )

    class Meta:
        ordering = ["-created_at"]
        unique_together = ["user", "message"]

simplesocial/accounts/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.db import models
from django import forms


class UserRegisterForm(UserCreationForm):

    username = forms.CharField(label='Display name')
    email = forms.EmailField(label='Email Address')

    class Meta:
        fields = ('username', 'email')
        model = User

simplesocial/accounts/views.py
from django.shortcuts import render

from django.urls import reverse_lazy
from django.views.generic import CreateView

from . import forms


class UserRegister(CreateView):
    form_class = forms.UserRegisterForm
    success_url = reverse_lazy('accounts:login')
    template_name = "accounts/register.html"

simplesocial/groups/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse
from django.views import generic
from .models import Group


class CreateGroup(LoginRequiredMixin, generic.CreateView):
    model = Group
    fields = ('name', 'description')


class SingleGroup(generic.DetailView):
    model = Group
    
class ListGroup(generic.ListView):
    model = Group

simplesocial/posts/views.py
from django.shortcuts import render

# Create your views here.

simplesocial/simplesocial/views.py
from django.views.generic import TemplateView


class HomePage(TemplateView):
    template_name = 'index.html'

simplesocial/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<div class="container">
    <h1>Log In</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary" value='Login'>
    </form>

</div>

{% endblock content %}

simplesocial/accounts/templates/accounts/logout.html
{% extends 'base.html' %}
{% block content %}
<h2>You have been logged out</h2>
<div class="border-top pt-3">
    <small class="text-muted">
        <a href="{% url 'accounts:login' %}">Log in Again</a>
    </small>
</div>

{% endblock %}

simplesocial/accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<div class="container">
    <h1>Sign Up</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-default" value='Sign Up'>
    </form>

</div>

{% endblock content %}

simplesocial/groups/templates/groups/group_base.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="row">

        {% block pregroup %}{% endblock pregroup %}
        {% block gruop_content %}{% endblock gruop_content %}
        {% block postgroup %}{% endblock postgroup %}

    </div>

</div>

{% endblock content %}

simplesocial/groups/templates/groups/group_detail.html
{% extends 'groups/group_base.html' %}

{% block pregroup %}
<h1>{{ group.name }}</h1>
<h2>{{ group.members.count }}</h2>

<div class="content">
    {% if user in group.members.all %}
    <a href="{% url 'groups:leave' slug=group.slug %}" class="btn btn-lg btn-fill btn-warning"><span
            class="glyphicon glyphicon-remove-circle">Leave</span></a>
    {% else %}
    <a href="{% url 'groups:join' slug=group.slug %}" class="btn btn-lg btn-fill btn-warning"><span
            class="glyphicon glyphicon-ok-circle">Join</span></a>
    {% endif %}

</div>
{% endblock pregroup %}
{% block group_content %}

<div class="col-md-8">
    {% if group.posts.count == 0 %}
    <h2>No posts in this group yet!</h2>

    {% else %}

    {% for post in group.posts.all %}
    {% include "posts/_post.html" %}
    {% endfor %}

    {% endif %}
</div>
{% endblock %}

simplesocial/groups/templates/groups/group_form.html
{% extends "groups/group_base.html" %}
{% load bootstrap3 %}

{% block group_content %}
<h4>Create A New Group</h4>
<form method="POST" action="{% url 'groups:create' %}" id="groupForm">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="Create" class="btn btn-primary btn-large">
</form>
{% endblock %}

simplesocial/groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %}

{% block pregroup %}
<div class="col-md-4">
    <div class="content">
        {% if user.is_authenticated %}
        <h2>
            Welcome back
            <a href="{% url 'posts:for_user' username=user.username %}">@{{user.username }}</a>
        </h2>

        {% endif %}
        <h2>Groups</h2>

        <p>Welcome to the Groups Page! Select a Group with a shared interest!</p>
    </div>
    {% if user.is_authenticated %}
    <a href="{% url 'groups:create' %}" class="btn btn-md btn-fill btn-warning"><span
            class="glyphicon glyphicon-plus-sign"></span> Create New Group!</a>
    {% endif %}
</div>
{% endblock %}

{% block group_content %}
<div class="col-md-8">
    <div class="list-group">
        {% for group in object_list %}
        <a class="list-group-item" href="{% url 'groups:single' slug=group.slug %}">
            <h3 class="title list-group-item-heading">{{ group.name }}</h3>
            <div class="list-group-item-text container-fluid">
                {{ group.description|safe }}
                <div class="row">
                    <div class="col-md-4">
                        <span class="badge">{{ group.members.count }}</span> member{{ group.members.count|pluralize }}
                    </div>
                    <div class="col-md-4">
                        <span class="badge">{{ group.posts.count }}</span> post{{ group.posts.count|pluralize }}
                    </div>
                </div>
            </div>
        </a>
        {% endfor %}
    </div>
</div>
{% endblock %}

simplesocial/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/master.css' %}">

    <title>Clarusway Social</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light mynav" role="navigation" id="navbar">
        <div class="container">
            <a class="navbar-brand mynav" href="{% url 'home' %}">Clarusway Social</a>

            <ul class="nav navbar-nav navbar-right">
                <li><a href="#" class="btn btn-simple">Groups</a></li>
                {% if user.is_authenticated %}
                <li><a href="#" class="btn btn-simple">Post</a></li>
                <li><a href="#" class="btn btn-simple">Create Group</a></li>
                <li><a href="{% url 'accounts:logout' %}" class="btn btn-simple">Logout</a></li>
                {% else %}
                <li><a href="{% url 'accounts:login' %}" class="btn btn-simple">Login</a></li>
                <li><a href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign Up</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="container mycontent">
        {% block content %}
        {% endblock content %}
    </div>



    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
        crossorigin="anonymous"></script>

</body>

</html>

simplesocial/templates/index.html
{% extends 'base.html' %}

{% block content %}

<body>
    <h1>Welcome</h1>
</body>
{% endblock content %}